# Generated by Django 5.2.17 on 2026-09-26 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Attendance Date')),
                ('clock_in_time', models.TimeField(blank=True, null=True, verbose_name='Clock In Time')),
                ('clock_out_time', models.TimeField(blank=True, null=True, verbose_name='Clock Out Time')),
                ('working_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Server-calculated total working hours', max_digits=5, verbose_name='Working Hours')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20, verbose_name='Attendance Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-clock_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
