# Generated by Django 5.2.17 on 2026-09-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Message')),
                ('notification_type', models.CharField(choices=[('LEAVE_APPLIED', 'Leave Applied'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('ATTENDANCE_REMINDER', 'Attendance Reminder'), ('DOCUMENT_EXPIRING', 'Document Expiring'), ('SYSTEM', 'System Alert')], db_index=True, default='SYSTEM', max_length=30, verbose_name='Type')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read Status')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Target Link URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
